in:
  type: file
  path_prefix: /tmp/yelp-dataset/checkin.csv
  parser:
    type: csv
    delimiter: \t
    charset: UTF-8
    newline: LF
    quote: '"'
    escape: '"'
    trim_if_not_quoted: false
    skip_header_lines: 0
    allow_extra_columns: false
    allow_optional_columns: false
    columns:
    - {name: c0, type: string}
out: {type: mysql, host: localhost, user: anderson, password: '1234567890', database: yelp,
  table: checkin, mode: replace}
