in:
  type: file
  path_prefix: /tmp/yelp-dataset/yelp_academic_dataset_tip.json
  parser:
    type: json
    columns:
    - {name: user_id, type: string}
    - {name: business_id, type: string}
    - {name: text, type: string}
    - {name: compliment_count, type: double}
    - {name: date, type: timestamp, format: '%Y-%m-%d %H:%M:%S'}
    charset: UTF-8
    newline: LF
out: {type: mysql, host: localhost, user: anderson, password: '1234567890', database: yelp,
  table: tip, mode: replace}
